---
### Ant
- name: 'make sure directory for Ant exists'
  file:
    dest: "{{ ant_base }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: 'verify presence of Ant'
  stat:
    path: "{{ ant_base }}/{{ ant_name }}/bin/ant"
  register: ant_installed
  when: features.ant

- name: 'untar Ant'
  unarchive:
    src: "{{ ant_url }}"
    dest: "{{ ant_base }}"
    copy: no
  retries: 3
  when: features.ant and not ant_installed.stat.exists

- name: 'install /etc/profile.d/ant.sh'
  template:
    src: etc-profile-d-ant-sh.j2
    dest: /etc/profile.d/ant.sh
    owner: root
    group: root
    mode: 0644
  when: features.ant

- name: 'make sure Ant directory is absent'
  file:
    dest: "{{ ant_base }}"
    state: absent
  when: not features.ant

- name: 'Test for presence of Ant'
  stat:
    path: "{{ ant_base }}/{{ ant_name }}/bin/ant"
  tags:
    - test
  when: features.ant

- name: 'set JAVA_HOME on Debian'
  become: yes
  set_fact:
    JAVA_HOME: '/usr/lib/jvm/jdk1.8.0_111'
  when: ansible_os_family == 'Debian'
  tags:
    - maven

- name: 'set JAVA_HOME on RedHat'
  become: yes
  set_fact:
    JAVA_HOME: '/usr/java/jdk1.8.0_111'
  when: ansible_os_family == 'RedHat' and features.ant
  tags:
    - maven

- name: 'Test running Ant'
  environment:
    JAVA_HOME: "{{ JAVA_HOME }}"
  command: "{{ ant_base }}/{{ ant_name }}/bin/ant -version"
  when: features.ant
  changed_when: no
  tags:
    - test
