---
### Ant
- name: 'make sure directory for Ant exists'
  file:
    dest: "{{ ant_base }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - ant

- name: 'verify presence of Ant'
  stat:
    path: "{{ ant_base }}/{{ ant_name }}/bin/ant"
  register: ant_installed
  when: features.ant
  tags:
    - ant
    - ant_test
    - test

- name: 'untar Ant'
  unarchive:
    src: "{{ ant_url }}"
    dest: "{{ ant_base }}"
    copy: no
  retries: 3
  when: features.ant and not ant_installed.stat.exists
  tags:
    - ant

- name: 'install /etc/profile.d/ant.sh'
  template:
    src: etc-profile-d-ant-sh.j2
    dest: /etc/profile.d/ant.sh
    owner: root
    group: root
    mode: 0644
  when: features.ant
  tags:
    - ant

- name: 'make sure Ant directory is absent'
  file:
    dest: "{{ ant_base }}"
    state: absent
  when: not features.ant
  tags:
    - ant

- name: 'Test for presence of Ant'
  stat:
    path: "{{ ant_base }}/{{ ant_name }}/bin/ant"
  when: features.ant
  tags:
    - ant
    - ant_test
    - test

- name: 'smoketest running Ant'
  environment:
    JAVA_HOME: "{{ java8_home }}"
  command: "{{ ant_base }}/{{ ant_name }}/bin/ant -version"
  when: features.ant
  changed_when: no
  tags:
    - ant
    - ant_test
    - test
