---

- name: 'Test for presence of Ant'
  become: no
  stat:
    path: "{{ ant_base }}/{{ ant_name }}/bin/ant"
  when: features.ant
  tags:
    - ant
    - ant_test
    - test

- name: 'smoketest running Ant'
  become: no
  environment:
    JAVA_HOME: "{{ java8_home }}"
  command: "{{ ansible_local.ant.ant.ant_home }}/bin/ant -version"
  when: features.ant
  changed_when: no
  tags:
    - ant
    - ant_test
    - test

- name: 'copy simple build.xml test file'
  become: no
  copy: src=build.xml dest=~/build.xml
  when: features.ant
  tags:
    - ant
    - ant_test
    - test

- name: 'functional test for ant'
  become: no
  environment:
    JAVA_HOME: "{{ java8_home }}"
    PATH: "{{ java8_home }}/bin/java:{{ ansible_env.PATH }}"
  command: "{{ ansible_local.ant.ant.ant_home }}/bin/ant -buildfile ~/build.xml"
  when: features.ant
  tags:
    - ant
    - ant_test
    - test

- name: 'remove build.xml test file'
  become: no
  file: dest=~/build.xml state=absent
  when: features.ant
  tags:
    - ant
    - ant_test
    - test
